version: "3"

services: 
  app:
    build: .
    command: npm start
    ports:
      - "5000:5000"
    volumes: 
      - .:/usr/img-process
    depends_on:
      - "mongo"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"